name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      PAGES_ARTIFACT_NAME: github-pages-${{ github.run_attempt }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install 3.10
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Build docs
        run: make docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          name: ${{ env.PAGES_ARTIFACT_NAME }}
          path: docs/_build/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: ${{ env.PAGES_ARTIFACT_NAME }}
